### ISSUE TITLE
Missing PIN needs better error message

### ISSUE THREAD

**Issue by jdalbey** [jdalbey/libbyfetch#9]
If the `library_card_config.txt` file has omitted the PIN field when it is required to sign in the program outputs an error as shown below.  This error isn't very informative or helpful. 
```
Initializing LibbyApp.
Reading library card configuration file.
Loading library page for 'sfpl'
Starting signin to San Francisco Public Library.
Library card number entered.
Traceback (most recent call last):
  File "/home/jdalbey/Docs/Computer/Projects/LibbyFetch/libbyfetch.py", line 159, in do_login_steps
    input_field.send_keys(library_pin)
  File "/home/jdalbey/Apps/pycharm/LibbyFetch/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 232, in send_keys
    Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
  File "/home/jdalbey/Apps/pycharm/LibbyFetch/lib/python3.10/site-packages/selenium/webdriver/common/utils.py", line 137, in keys_to_typing
    characters.extend(val)
TypeError: 'NoneType' object is not iterable
An error occurred filling PIN:
```

**Comment by jdalbey** [comment]
FIxed in https://github.com/jdalbey/libbyfetch/commit/7993da7732c6305e653bf2bc8034a6fef67ce28b 
Closing.
